package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/nahmanmate/goanna/transpiler/pipeline"
)

// transpile subcommand (default when no subcommand given)
var cli struct {
	Files  []string `arg:"" optional:"" help:"Input .goa files. Reads stdin if none given."`
	Output string   `short:"o" help:"Output file. Defaults to <input>.go (strips .union). Use - for stdout."`
	Check  bool     `help:"Validate only; do not emit output."`
}

// default set below but actual version is inserted by CI from release tag
var version = "dev"

func main() {
	if len(os.Args) > 1 {
		if os.Args[1] == "--version" || os.Args[1] == "-version" {
			_, err := fmt.Println("goanna", version)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			}
			return
		}
		if os.Args[1] == "build" {
			if err := runBuild(os.Args[2:]); err != nil {
				var exitErr *exec.ExitError
				if errors.As(err, &exitErr) {
					os.Exit(exitErr.ExitCode())
				}
				fatalf("%v", err)
			}
			return
		}
	}

	kong.Parse(&cli)

	if len(cli.Files) == 0 {
		var buf bytes.Buffer
		src, err := io.ReadAll(os.Stdin)
		if err != nil {
			fatalf("read stdin: %v", err)
		}
		if err := pipeline.Transpile(src, "<stdin>", &buf); err != nil {
			fatalf("%v", err)
		}
		if !cli.Check {
			if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
				fatalf("write stdout: %v", err)
			}
		}
		return
	}

	goannaDirs := make(map[string]bool)
	for _, input := range cli.Files {
		if err := processFile(input, goannaDirs); err != nil {
			fatalf("%v", err)
		}
	}
}

func processFile(input string, goannaDirs map[string]bool) error {
	outPath := cli.Output
	if outPath == "" {
		outPath = stripUnionExt(input)
	}

	var buf bytes.Buffer
	usesAtom, pkgName, err := pipeline.TranspileFileEx(input, &buf)
	if err != nil {
		return err
	}
	if cli.Check {
		return nil
	}

	header := fmt.Sprintf("// Code generated by goanna. DO NOT EDIT.\n// Source: %s\n\n",
		filepath.Base(input))
	out := append([]byte(header), buf.Bytes()...)

	if outPath == "-" {
		_, err := os.Stdout.Write(out)
		return err
	}
	if err := os.WriteFile(outPath, out, 0o644); err != nil {
		return err
	}

	if usesAtom && cli.Output == "" && goannaDirs != nil {
		dir := filepath.Dir(outPath)
		if !goannaDirs[dir] {
			goannaDirs[dir] = true
			if err := writeGoannTypes(dir, pkgName); err != nil {
				return err
			}
		}
	}
	return nil
}

// runBuild handles: goanna build [--keep] [--check] [patterns...]
func runBuild(args []string) error {
	var keep, check bool
	var patterns []string

	for _, a := range args {
		switch a {
		case "--keep", "-k":
			keep = true
		case "--check":
			check = true
		default:
			patterns = append(patterns, a)
		}
	}
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	unionFiles, err := findUnionFiles(patterns)
	if err != nil {
		return err
	}

	if check {
		return checkUnionFiles(unionFiles)
	}

	if keep {
		type keepResult struct {
			dst      string
			pkgName  string
			usesAtom bool
			err      error
		}
		ch := make(chan keepResult, len(unionFiles))
		for _, src := range unionFiles {
			go func(src string) {
				dst := stripUnionExt(src)
				usesAtom, pkgName, err := writeTranspiled(src, dst)
				ch <- keepResult{dst: dst, pkgName: pkgName, usesAtom: usesAtom, err: err}
			}(src)
		}
		goannaDirs := make(map[string]bool)
		for range unionFiles {
			r := <-ch
			if r.err != nil {
				return r.err
			}
			if r.usesAtom {
				dir := filepath.Dir(r.dst)
				if !goannaDirs[dir] {
					goannaDirs[dir] = true
					if err := writeGoannTypes(dir, r.pkgName); err != nil {
						return err
					}
				}
			}
		}
		return goBuild(patterns, "")
	}

	return buildWithOverlay(unionFiles, patterns)
}

func checkUnionFiles(unionFiles []string) error {
	type result struct{ err error }
	ch := make(chan result, len(unionFiles))
	for _, src := range unionFiles {
		go func(src string) {
			ch <- result{pipeline.TranspileFile(src, io.Discard)}
		}(src)
	}
	var errs []string
	for range unionFiles {
		if r := <-ch; r.err != nil {
			errs = append(errs, r.err.Error())
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("%s", strings.Join(errs, "\n"))
	}
	return nil
}

func buildWithOverlay(unionFiles []string, patterns []string) error {
	if len(unionFiles) == 0 {
		return goBuild(patterns, "")
	}

	tmpDir, err := os.MkdirTemp("", "goanna-*")
	if err != nil {
		return fmt.Errorf("mktemp: %w", err)
	}
	defer os.RemoveAll(tmpDir) //nolint:errcheck

	type overlayResult struct {
		abs      string
		dst      string
		absDir   string
		pkgName  string
		usesAtom bool
		err      error
	}
	ch := make(chan overlayResult, len(unionFiles))
	for i, src := range unionFiles {
		go func(i int, src string) {
			abs, err := filepath.Abs(src)
			if err != nil {
				ch <- overlayResult{err: err}
				return
			}
			dst := filepath.Join(tmpDir, fmt.Sprintf("%d.go", i))
			usesAtom, pkgName, err := writeTranspiled(src, dst)
			ch <- overlayResult{
				abs: abs, dst: dst, absDir: filepath.Dir(abs),
				pkgName: pkgName, usesAtom: usesAtom, err: err,
			}
		}(i, src)
	}

	replace := make(map[string]string, len(unionFiles))
	atomPkgs := make(map[string]string) // absDir → pkgName
	for range unionFiles {
		r := <-ch
		if r.err != nil {
			return r.err
		}
		replace[r.abs] = r.dst
		if r.usesAtom {
			if _, seen := atomPkgs[r.absDir]; !seen {
				atomPkgs[r.absDir] = r.pkgName
			}
		}
	}

	// Emit goanna_types.go for each atom-using package via overlay.
	typesIdx := 0
	for absDir, pkgName := range atomPkgs {
		content := fmt.Sprintf("// Code generated by goanna. DO NOT EDIT.\n\npackage %s\n\ntype atom struct{}\n", pkgName)
		tmpTypes := filepath.Join(tmpDir, fmt.Sprintf("goanna_types_%d.go", typesIdx))
		typesIdx++
		if err := os.WriteFile(tmpTypes, []byte(content), 0o644); err != nil {
			return err
		}
		replace[filepath.Join(absDir, "goanna_types.go")] = tmpTypes
	}

	overlayData, err := json.Marshal(struct{ Replace map[string]string }{replace})
	if err != nil {
		return err
	}
	overlayFile := filepath.Join(tmpDir, "overlay.json")
	if err := os.WriteFile(overlayFile, overlayData, 0o644); err != nil {
		return err
	}

	return goBuild(patterns, overlayFile)
}

func goBuild(patterns []string, overlayFile string) error {
	args := []string{"build"}
	if overlayFile != "" {
		args = append(args, "-overlay="+overlayFile)
	}
	args = append(args, patterns...)
	cmd := exec.Command("go", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func writeTranspiled(src, dst string) (usesAtom bool, pkgName string, err error) {
	var buf bytes.Buffer
	usesAtom, pkgName, err = pipeline.TranspileFileEx(src, &buf)
	if err != nil {
		return false, "", err
	}
	header := fmt.Sprintf("// Code generated by goanna. DO NOT EDIT.\n// Source: %s\n\n",
		filepath.Base(src))
	out := append([]byte(header), buf.Bytes()...)
	return usesAtom, pkgName, os.WriteFile(dst, out, 0o644)
}

// writeGoannTypes writes goanna_types.go to dir with the given package name.
func writeGoannTypes(dir, pkgName string) error {
	content := fmt.Sprintf("// Code generated by goanna. DO NOT EDIT.\n\npackage %s\n\ntype atom struct{}\n", pkgName)
	return os.WriteFile(filepath.Join(dir, "goanna_types.go"), []byte(content), 0o644)
}

func findUnionFiles(patterns []string) ([]string, error) {
	seen := make(map[string]bool)
	var files []string

	add := func(p string) error {
		abs, err := filepath.Abs(p)
		if err != nil {
			return err
		}
		if !seen[abs] {
			seen[abs] = true
			files = append(files, abs)
		}
		return nil
	}

	for _, p := range patterns {
		if strings.HasSuffix(p, ".goa") {
			if err := add(p); err != nil {
				return nil, err
			}
			continue
		}

		if strings.HasSuffix(p, "...") {
			root := filepath.Dir(strings.TrimSuffix(p, "..."))
			if root == "" {
				root = "."
			}
			err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if d.IsDir() {
					if d.Name() == "vendor" || strings.HasPrefix(d.Name(), ".") {
						return filepath.SkipDir
					}
					return nil
				}
				if strings.HasSuffix(path, ".goa") {
					return add(path)
				}
				return nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}

		// Single directory (non-recursive)
		entries, err := os.ReadDir(p)
		if err != nil {
			return nil, fmt.Errorf("readdir %s: %w", p, err)
		}
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".goa") {
				if err := add(filepath.Join(p, e.Name())); err != nil {
					return nil, err
				}
			}
		}
	}

	return files, nil
}

func stripUnionExt(name string) string {
	base := filepath.Base(name)
	dir := filepath.Dir(name)
	if strings.HasSuffix(base, ".goa") {
		base = strings.TrimSuffix(base, ".goa") + ".go"
	}
	return filepath.Join(dir, base)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "goanna: "+format+"\n", args...)
	os.Exit(1)
}
