package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/nahmanmate/gounion/internal/pipeline"
)

// transpile subcommand (default when no subcommand given)
var cli struct {
	Files  []string `arg:"" optional:"" help:"Input .union.go files. Reads stdin if none given."`
	Output string   `short:"o" help:"Output file. Defaults to <input>.go (strips .union). Use - for stdout."`
	Check  bool     `help:"Validate only; do not emit output."`
}

func main() {
	if len(os.Args) > 1 && os.Args[1] == "build" {
		if err := runBuild(os.Args[2:]); err != nil {
			var exitErr *exec.ExitError
			if errors.As(err, &exitErr) {
				os.Exit(exitErr.ExitCode())
			}
			fatalf("%v", err)
		}
		return
	}

	kong.Parse(&cli)

	if len(cli.Files) == 0 {
		var buf bytes.Buffer
		src, err := io.ReadAll(os.Stdin)
		if err != nil {
			fatalf("read stdin: %v", err)
		}
		if err := pipeline.Transpile(src, "<stdin>", &buf); err != nil {
			fatalf("%v", err)
		}
		if !cli.Check {
			os.Stdout.Write(buf.Bytes())
		}
		return
	}

	for _, input := range cli.Files {
		if err := processFile(input); err != nil {
			fatalf("%v", err)
		}
	}
}

func processFile(input string) error {
	outPath := cli.Output
	if outPath == "" {
		outPath = stripUnionExt(input)
	}

	var buf bytes.Buffer
	if err := pipeline.TranspileFile(input, &buf); err != nil {
		return err
	}
	if cli.Check {
		return nil
	}

	header := fmt.Sprintf("// Code generated by gounion. DO NOT EDIT.\n// Source: %s\n\n",
		filepath.Base(input))
	out := append([]byte(header), buf.Bytes()...)

	if outPath == "-" {
		_, err := os.Stdout.Write(out)
		return err
	}
	return os.WriteFile(outPath, out, 0644)
}

// runBuild handles: gounion build [--keep] [patterns...]
func runBuild(args []string) error {
	var keep bool
	var patterns []string

	for _, a := range args {
		switch a {
		case "--keep", "-k":
			keep = true
		default:
			patterns = append(patterns, a)
		}
	}
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	unionFiles, err := findUnionFiles(patterns)
	if err != nil {
		return err
	}

	if keep {
		for _, src := range unionFiles {
			if err := writeTranspiled(src, stripUnionExt(src)); err != nil {
				return err
			}
		}
		return goBuild(patterns, "")
	}

	return buildWithOverlay(unionFiles, patterns)
}

func buildWithOverlay(unionFiles []string, patterns []string) error {
	if len(unionFiles) == 0 {
		return goBuild(patterns, "")
	}

	tmpDir, err := os.MkdirTemp("", "gounion-*")
	if err != nil {
		return fmt.Errorf("mktemp: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	replace := make(map[string]string)
	for i, src := range unionFiles {
		abs, err := filepath.Abs(src)
		if err != nil {
			return err
		}
		dst := filepath.Join(tmpDir, fmt.Sprintf("%d.go", i))
		if err := writeTranspiled(src, dst); err != nil {
			return err
		}
		replace[abs] = dst
	}

	overlayData, err := json.Marshal(struct{ Replace map[string]string }{replace})
	if err != nil {
		return err
	}
	overlayFile := filepath.Join(tmpDir, "overlay.json")
	if err := os.WriteFile(overlayFile, overlayData, 0644); err != nil {
		return err
	}

	return goBuild(patterns, overlayFile)
}

func goBuild(patterns []string, overlayFile string) error {
	args := []string{"build"}
	if overlayFile != "" {
		args = append(args, "-overlay="+overlayFile)
	}
	args = append(args, patterns...)
	cmd := exec.Command("go", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func writeTranspiled(src, dst string) error {
	var buf bytes.Buffer
	if err := pipeline.TranspileFile(src, &buf); err != nil {
		return err
	}
	header := fmt.Sprintf("// Code generated by gounion. DO NOT EDIT.\n// Source: %s\n\n",
		filepath.Base(src))
	out := append([]byte(header), buf.Bytes()...)
	return os.WriteFile(dst, out, 0644)
}

func findUnionFiles(patterns []string) ([]string, error) {
	seen := make(map[string]bool)
	var files []string

	add := func(p string) error {
		abs, err := filepath.Abs(p)
		if err != nil {
			return err
		}
		if !seen[abs] {
			seen[abs] = true
			files = append(files, abs)
		}
		return nil
	}

	for _, p := range patterns {
		if strings.HasSuffix(p, ".union.go") {
			if err := add(p); err != nil {
				return nil, err
			}
			continue
		}

		if strings.HasSuffix(p, "...") {
			root := filepath.Dir(strings.TrimSuffix(p, "..."))
			if root == "" {
				root = "."
			}
			err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if d.IsDir() {
					if d.Name() == "vendor" || strings.HasPrefix(d.Name(), ".") {
						return filepath.SkipDir
					}
					return nil
				}
				if strings.HasSuffix(path, ".union.go") {
					return add(path)
				}
				return nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}

		// Single directory (non-recursive)
		entries, err := os.ReadDir(p)
		if err != nil {
			return nil, fmt.Errorf("readdir %s: %w", p, err)
		}
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".union.go") {
				if err := add(filepath.Join(p, e.Name())); err != nil {
					return nil, err
				}
			}
		}
	}

	return files, nil
}

func stripUnionExt(name string) string {
	base := filepath.Base(name)
	dir := filepath.Dir(name)
	if strings.HasSuffix(base, ".union.go") {
		base = strings.TrimSuffix(base, ".union.go") + ".go"
	}
	return filepath.Join(dir, base)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gounion: "+format+"\n", args...)
	os.Exit(1)
}
