package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/nahmanmate/gounion/internal/pipeline"
)

var cli struct {
	Files  []string `arg:"" optional:"" help:"Input .union.go files. Reads stdin if none given."`
	Output string   `short:"o" help:"Output file. Defaults to <input>.go (strips .union). Use - for stdout."`
	Check  bool     `help:"Validate only; do not emit output."`
}

func main() {
	kong.Parse(&cli)

	if len(cli.Files) == 0 {
		// stdin → stdout
		var buf bytes.Buffer
		src, err := io.ReadAll(os.Stdin)
		if err != nil {
			fatalf("read stdin: %v", err)
		}
		if err := pipeline.Transpile(src, "<stdin>", &buf); err != nil {
			fatalf("%v", err)
		}
		if !cli.Check {
			os.Stdout.Write(buf.Bytes())
		}
		return
	}

	for _, input := range cli.Files {
		if err := processFile(input); err != nil {
			fatalf("%v", err)
		}
	}
}

func processFile(input string) error {
	outPath := cli.Output
	if outPath == "" {
		outPath = stripUnionExt(input)
	}

	var buf bytes.Buffer
	if err := pipeline.TranspileFile(input, &buf); err != nil {
		return err
	}

	if cli.Check {
		return nil
	}

	header := fmt.Sprintf("// Code generated by gounion. DO NOT EDIT.\n// Source: %s\n\n",
		filepath.Base(input))

	out := append([]byte(header), buf.Bytes()...)

	if outPath == "-" {
		_, err := os.Stdout.Write(out)
		return err
	}
	return os.WriteFile(outPath, out, 0644)
}

func stripUnionExt(name string) string {
	// "foo.union.go" → "foo.go"
	// "foo.go"       → "foo.go"  (passthrough)
	base := filepath.Base(name)
	dir := filepath.Dir(name)
	if strings.HasSuffix(base, ".union.go") {
		base = strings.TrimSuffix(base, ".union.go") + ".go"
	}
	return filepath.Join(dir, base)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gounion: "+format+"\n", args...)
	os.Exit(1)
}
